### ISSUE TITLE
Compile Problem

### ISSUE THREAD

**Issue by ngnnb** [BugenZhao/flashroute.rs#19]
The environment has been built，but which path should I compile in? I try compiling in this path,but failed.

~/FlashRoute-0.1.0# bazel build flashroute

The error is below

/root/FlashRoute-0.1.0/WORKSPACE:38:15: in <toplevel>
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'com_github_nelhage_rules_boost':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "/root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "/root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "/root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
                init(ctx, git_repo)
        File "/root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
                _error(ctx.name, cl, st.stderr)
        File "/root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init /root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/com_github_nelhage_rules_boost' while working with @com_github_nelhage_rules_boost:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "/root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "/root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "/root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
                init(ctx, git_repo)
        File "/root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
                _error(ctx.name, cl, st.stderr)
        File "/root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init /root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/com_github_nelhage_rules_boost' while working with @com_github_nelhage_rules_boost:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
ERROR: no such package '@com_github_nelhage_rules_boost//boost': error running 'git init /root/.cache/bazel/_bazel_root/6756548e03526d6223b176b5c6e8421d/external/com_github_nelhage_rules_boost' while working with @com_github_nelhage_rules_boost:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory

**Comment by BugenZhao** [comment]
It seems that you are reporting a compiling problem of the original C++ version of FlashRoute (https://github.com/lambdahuang/FlashRoute). I suggest opening an issue there :)
